Reauthentication required.
Traceback (most recent call last):
  File "/Users/mcnatt/google-cloud-sdk/platform/gsutil/gsutil", line 21, in <module>
    gsutil.RunMain()
  File "/Users/mcnatt/google-cloud-sdk/platform/gsutil/gsutil.py", line 158, in RunMain
    sys.exit(gslib.__main__.main())
  File "/Users/mcnatt/google-cloud-sdk/platform/gsutil/gslib/__main__.py", line 436, in main
    return _RunNamedCommandAndHandleExceptions(
  File "/Users/mcnatt/google-cloud-sdk/platform/gsutil/gslib/__main__.py", line 786, in _RunNamedCommandAndHandleExceptions
    _HandleUnknownFailure(e)
  File "/Users/mcnatt/google-cloud-sdk/platform/gsutil/gslib/__main__.py", line 633, in _RunNamedCommandAndHandleExceptions
    return command_runner.RunNamedCommand(command_name,
  File "/Users/mcnatt/google-cloud-sdk/platform/gsutil/gslib/command_runner.py", line 421, in RunNamedCommand
    return_code = command_inst.RunCommand()
  File "/Users/mcnatt/google-cloud-sdk/platform/gsutil/gslib/commands/cp.py", line 1131, in RunCommand
    self.Apply(_CopyFuncWrapper,
  File "/Users/mcnatt/google-cloud-sdk/platform/gsutil/gslib/command.py", line 1575, in Apply
    self._SequentialApply(func, args_iterator, exception_handler, caller_id,
  File "/Users/mcnatt/google-cloud-sdk/platform/gsutil/gslib/command.py", line 1627, in _SequentialApply
    args = next(args_iterator)
  File "/Users/mcnatt/google-cloud-sdk/platform/gsutil/gslib/name_expansion.py", line 687, in __next__
    name_expansion_result = next(self.current_expansion_iter)
  File "/Users/mcnatt/google-cloud-sdk/platform/gsutil/gslib/plurality_checkable_iterator.py", line 96, in __next__
    raise six.reraise(item_tuple[1].__class__, item_tuple[1], item_tuple[2])
  File "/Users/mcnatt/google-cloud-sdk/platform/gsutil/third_party/six/six.py", line 719, in reraise
    raise value
  File "/Users/mcnatt/google-cloud-sdk/platform/gsutil/gslib/plurality_checkable_iterator.py", line 70, in _PopulateHead
    e = next(self.base_iterator)
  File "/Users/mcnatt/google-cloud-sdk/platform/gsutil/gslib/name_expansion.py", line 291, in __iter__
    for (names_container, blr) in post_step3_iter:
  File "/Users/mcnatt/google-cloud-sdk/platform/gsutil/gslib/plurality_checkable_iterator.py", line 96, in __next__
    raise six.reraise(item_tuple[1].__class__, item_tuple[1], item_tuple[2])
  File "/Users/mcnatt/google-cloud-sdk/platform/gsutil/third_party/six/six.py", line 719, in reraise
    raise value
  File "/Users/mcnatt/google-cloud-sdk/platform/gsutil/gslib/plurality_checkable_iterator.py", line 70, in _PopulateHead
    e = next(self.base_iterator)
  File "/Users/mcnatt/google-cloud-sdk/platform/gsutil/gslib/name_expansion.py", line 533, in __iter__
    for (names_container, blr) in self.tuple_iter:
  File "/Users/mcnatt/google-cloud-sdk/platform/gsutil/gslib/plurality_checkable_iterator.py", line 96, in __next__
    raise six.reraise(item_tuple[1].__class__, item_tuple[1], item_tuple[2])
  File "/Users/mcnatt/google-cloud-sdk/platform/gsutil/third_party/six/six.py", line 719, in reraise
    raise value
  File "/Users/mcnatt/google-cloud-sdk/platform/gsutil/gslib/plurality_checkable_iterator.py", line 70, in _PopulateHead
    e = next(self.base_iterator)
  File "/Users/mcnatt/google-cloud-sdk/platform/gsutil/gslib/name_expansion.py", line 497, in __iter__
    for blr in self.blr_iter:
  File "/Users/mcnatt/google-cloud-sdk/platform/gsutil/gslib/plurality_checkable_iterator.py", line 96, in __next__
    raise six.reraise(item_tuple[1].__class__, item_tuple[1], item_tuple[2])
  File "/Users/mcnatt/google-cloud-sdk/platform/gsutil/third_party/six/six.py", line 719, in reraise
    raise value
  File "/Users/mcnatt/google-cloud-sdk/platform/gsutil/gslib/plurality_checkable_iterator.py", line 70, in _PopulateHead
    e = next(self.base_iterator)
  File "/Users/mcnatt/google-cloud-sdk/platform/gsutil/gslib/wildcard_iterator.py", line 538, in IterAll
    for blr in self.__iter__(bucket_listing_fields=bucket_listing_fields,
  File "/Users/mcnatt/google-cloud-sdk/platform/gsutil/gslib/wildcard_iterator.py", line 189, in __iter__
    get_object = self.gsutil_api.GetObjectMetadata(
  File "/Users/mcnatt/google-cloud-sdk/platform/gsutil/gslib/cloud_api_delegator.py", line 314, in GetObjectMetadata
    return self._GetApi(provider).GetObjectMetadata(bucket_name,
  File "/Users/mcnatt/google-cloud-sdk/platform/gsutil/gslib/gcs_json_api.py", line 1047, in GetObjectMetadata
    object_metadata = self._GetObjectMetadataHelper(bucket_name,
  File "/Users/mcnatt/google-cloud-sdk/platform/gsutil/gslib/gcs_json_api.py", line 1004, in _GetObjectMetadataHelper
    return self.api_client.objects.Get(apitools_request,
  File "/Users/mcnatt/google-cloud-sdk/platform/gsutil/gslib/third_party/storage_apitools/storage_v1_client.py", line 1124, in Get
    return self._RunMethod(
  File "/Users/mcnatt/google-cloud-sdk/platform/gsutil/third_party/apitools/apitools/base/py/base_api.py", line 734, in _RunMethod
    http_response = http_wrapper.MakeRequest(
  File "/Users/mcnatt/google-cloud-sdk/platform/gsutil/third_party/apitools/apitools/base/py/http_wrapper.py", line 359, in MakeRequest
    retry_func(ExceptionRetryArgs(http, http_request, e, retry,
  File "/Users/mcnatt/google-cloud-sdk/platform/gsutil/gslib/utils/retry_util.py", line 65, in WarnAfterManyRetriesHandler
    http_wrapper.HandleExceptionsAndRebuildHttpConnections(retry_args)
  File "/Users/mcnatt/google-cloud-sdk/platform/gsutil/third_party/apitools/apitools/base/py/http_wrapper.py", line 304, in HandleExceptionsAndRebuildHttpConnections
    raise retry_args.exc
  File "/Users/mcnatt/google-cloud-sdk/platform/gsutil/third_party/apitools/apitools/base/py/http_wrapper.py", line 348, in MakeRequest
    return _MakeRequestNoRetry(
  File "/Users/mcnatt/google-cloud-sdk/platform/gsutil/third_party/apitools/apitools/base/py/http_wrapper.py", line 397, in _MakeRequestNoRetry
    info, content = http.request(
  File "/Users/mcnatt/google-cloud-sdk/platform/gsutil/gslib/vendored/oauth2client/oauth2client/transport.py", line 159, in new_request
    credentials._refresh(orig_request_method)
  File "/Users/mcnatt/google-cloud-sdk/platform/gsutil/gslib/vendored/oauth2client/oauth2client/client.py", line 761, in _refresh
    self._do_refresh_request(http)
  File "/Users/mcnatt/google-cloud-sdk/platform/gsutil/third_party/google-reauth-python/google_reauth/reauth_creds.py", line 112, in _do_refresh_request
    self._update(*reauth.refresh_access_token(
  File "/Users/mcnatt/google-cloud-sdk/platform/gsutil/third_party/google-reauth-python/google_reauth/reauth.py", line 283, in refresh_access_token
    rapt = get_rapt_token(
  File "/Users/mcnatt/google-cloud-sdk/platform/gsutil/third_party/google-reauth-python/google_reauth/reauth.py", line 194, in get_rapt_token
    rapt_token = _obtain_rapt(
  File "/Users/mcnatt/google-cloud-sdk/platform/gsutil/third_party/google-reauth-python/google_reauth/reauth.py", line 142, in _obtain_rapt
    raise errors.ReauthUnattendedError()
google_reauth.errors.ReauthUnattendedError: Reauthentication challenge could not be answered because you are not in an interactive session.
